### PR TITLE
Add missing cast of type object for decimal scalar

### PR DESCRIPTION
**Pull request by c7h**
I'm running into this weird problem where my DecimalScalar return with type _object_. This PR fixes this Issues.

### CODE REVIEW

**Comment by Cauen** [comment]
Hello @c7h 

I couldn't understand your use case
In the code, we reject all inputs other than string and number
In which case are you going to correctly convert an object to a float before inserting it into a "decimal" column?

**Comment by c7h** [comment]
> In the code, we reject all inputs other than string and number

this is exactly the problem I'm trying to solve. For some reason, I'm receiving this.

Debugger view with updated code snippet

I am not sure why I am receiving an object instead of an int or a float.

**Comment by Cauen** [comment]
You're correct. 

`typeof new Number(7.78) === "object"`

I'll expand your code to date and accept.
Thanks for contributing :D

**Comment by c7h** [comment]
Hi @Cauen! any updates on this one? :-)

**Comment by Cauen** [comment]
Merged, thanks @c7h \o/

**Comment by c7h** [comment]
many thanks! works like a charm! ⭐

**Pull request merged**
