### PR TITLE
Generate 'ID' fields in input types

### PR DESCRIPTION
**Pull request by hbendev**
See https://github.com/Cauen/prisma-generator-pothos-codegen/issues/50

### CODE REVIEW

**Comment by Cauen** [comment]
Thanks for your contribution @hbendev 
You implemented just for string Ids. Why not for any id?

**Comment by hbendev** [comment]
Okay, I'll transform integer id fields too. I was strict, because according to the [GraphQL specification](https://spec.graphql.org/October2021/#sec-ID) only integer and string input values should be accepted as IDs.

However, Prisma supports declaring any scalar field as an id, so I'm a little lost on whether this is the most correct solution. https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#id

**Comment by hbendev** [comment]
Hi @Cauen Can this fix get merged and released? After reading the prisma docs more carefully, all *scalars*  should be allowed. I'll try make that change soon.

**Comment by hbendev** [comment]
Also, I want to note that this is unfortunately a breaking change.

**Pull request merged**
